.PHONY: test bench example tidy clean

# Run standard unit tests
test:
	go test -v ./...

# Run benchmark tests with memory allocation tracking
bench:
	go test -bench=. -benchmem ./dletter/...

# Run the example application
example:
	go run cmd/example/main.go

# Tidy module dependencies
tidy:
	go mod tidy

# Clean up log outputs generated by testing or example runs
clean:
	rm -rf logs/*.log
	rm -rf test_*.log
